### ISSUE TITLE
Not compatible with IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by AleksejsGrocevs** [knusperleicht/intellij-quasar#13]
Please update the plugin

**Comment by nucle** [comment]
thank will do it on the weekend.

**Comment by dxvgef** [comment]
> thank will do it on the weekend.

Thank you for your work

**Comment by nucle** [comment]
Uploaded to JetBrains marketplace

JetBrains is reviewing this update. Please expect it to be approved within two business days of the upload.
