### ISSUE TITLE
Not compatible with IntelliJ 2024.3

### ISSUE THREAD

**Issue by roberttolton** [knusperleicht/intellij-quasar#16]
Hi, thanks for your work on this plugin.

What's involved with making it compatible with IntelliJ 2024.3?

**Comment by nucle** [comment]
Thank you!
Will update the plugin this week.
-> 2024.3

**Comment by nucle** [comment]
-> Artifact published, waiting for release.
We haven’t found any problems with your plugin so far! Before your plugin update is published, our Support team will conduct some additional checks. This can take up to 2 business days.
-> Download Version [done]
